FROM mysql:8.0

ENV host=localhost
ENV port=3306
#senha do banco
ENV MYSQL_PASSWORD=root
ENV MYSQL_USER=admin
ENV MYSQL_ROOT_PASSWORD=1234
ENV MYSQL_DATABASE=rocketDB

EXPOSE 3306

#ENV devem estar em maiuscula